StylesPath = styles
MinAlertLevel = suggestion
StylesPath = .github/styles
Vocab = Velociraptor

# We don't check content that comes from the Velociraptor repo because it should rather be checked at the source.
[content/{announcements,blog,dev,docs,downloads,knowledge_base,rss,training}/**/*.md]

# Will run all the rules in these style folders unless they are individually forbidden like the Vale ones below.
BasedOnStyles = Vale, Velociraptor

# Vale.Spelling is replaced by Spelling-Dictionaries which we can customize.
Vale.Spelling = NO


# Informational - if you don't want to see this you can disable them with = NO
Metrics.complex_words = YES
Metrics.long_words = YES
Metrics.polysyllabic_words = YES

# A utility rule for identifying which content is being parsed into which scope, during rule dev/testing.
Test.DumpScopes = NO

