StylesPath = styles
MinAlertLevel = suggestion
StylesPath = .github/styles
Vocab = Velociraptor

# [content/{announcements,blog,dev,docs,downloads,knowledge_base,rss,training}/**/*.md]
[content/{announcements,knowledge_base}/**/*.md]

BasedOnStyles = Velociraptor

# Vale.Terms is replaced by XXXX - accept.txt is a waste of time
Vale.Terms = NO
# Vale.Spelling is replaced by Spelling.Dictionaries
Vale.Spelling = NO
# Vale.Avoid is replaced by Terms.Avoid
Vale.Avoid = NO
# Vale.Repetition is replaced by Grammar.WordRepetition
Vale.Repetition = NO

#Metrics.characters = YES
#Metrics.complex_words = YES
#Metrics.long_words = YES
#Metrics.polysyllabic_words = YES
#Metrics.paragraphs = YES
#Metrics.sentences = YES
Metrics.words = NO

# Test.DumpScopes = NO

