name: Vale Linter Action
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vale:
    name: vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vale-cli/vale-action@v2.1.1
